const majorData=[
['Le Mat','Élan · liberté','Un voyageur avance au bord d’un précipice, accompagné d’un chien et portant un petit baluchon.','Un nouveau départ, la spontanéité et la confiance dans l’inconnu. Invite à oser, tout en gardant conscience du chemin.'],
['Le Bateleur','Initiative · potentiel','Un personnage se tient devant une table où reposent coupe, épée, bâton et denier; une main montre le ciel.','La capacité de transformer une idée en action. Les ressources sont déjà présentes : il reste à les utiliser avec intention.'],
['La Papesse','Intuition · savoir intérieur','Une femme assise entre deux colonnes tient un rouleau; un voile cache ce qui se trouve derrière elle.','Écouter son intuition, observer et laisser mûrir ce qui n’est pas encore prêt à être dévoilé.'],
['L’Impératrice','Création · abondance','Une souveraine est assise au milieu des champs, entourée de blé, de nature et d’un coussin orné de Vénus.','Fertilité des idées, soin et croissance. Une invitation à nourrir un projet ou une relation.'],
['L’Empereur','Structure · stabilité','Un souverain siège sur un trône de pierre décoré de béliers, devant un paysage montagneux.','Cadre, responsabilité et pouvoir de décision. Construire des bases solides et prendre sa place.'],
['Le Pape','Transmission · tradition','Un guide spirituel bénit deux disciples, assis entre des colonnes, avec des clefs à ses pieds.','Enseignement, valeurs partagées et recherche de sens auprès d’une tradition ou d’un mentor.'],
['L’Amoureux','Choix · lien','Un couple se tient sous un ange et un soleil; derrière eux apparaissent l’arbre de vie et l’arbre de la connaissance.','Relation, accord profond et décision fidèle à ses valeurs. Le choix demande de la sincérité.'],
['Le Chariot','Volonté · direction','Un conducteur en armure se tient dans un char tiré par deux sphinx de couleurs opposées.','Avancer avec détermination en donnant une direction commune à des forces contraires.'],
['La Force','Courage · douceur','Une femme ferme calmement la gueule d’un lion; le signe de l’infini flotte au-dessus d’elle.','Maîtrise de soi, patience et courage tranquille. La douceur peut dompter ce que la force brute ne résout pas.'],
['L’Hermite','Retrait · discernement','Un vieil homme marche seul dans la neige avec une lanterne et un bâton.','Prendre du recul pour éclairer une question intérieure. La solitude choisie aide à distinguer l’essentiel.'],
['La Roue de Fortune','Cycle · changement','Une roue portant des symboles tourne au milieu de figures ailées et de créatures mythiques.','Les situations évoluent. Accueillir un tournant, reconnaître les cycles et s’adapter à ce qui bouge.'],
['La Justice','Équilibre · décision','Une figure couronnée tient une épée droite et une balance, assise entre deux piliers.','Peser les faits, assumer ses actes et rechercher une décision juste et proportionnée.'],
['Le Pendu','Pause · perspective','Un homme pend par un pied à un arbre, le visage serein et entouré d’un halo.','Faire une pause volontaire et regarder autrement. L’attente peut révéler ce que l’action cachait.'],
['L’Arcane sans nom','Fin · transformation','Un squelette en armure avance sur un cheval blanc, tenant une bannière ornée d’une rose.','La fin d’un cycle ouvre la voie à un renouveau. Il s’agit souvent de laisser partir une forme ancienne.'],
['Tempérance','Mesure · harmonie','Un ange verse de l’eau d’une coupe à l’autre, un pied sur la terre et l’autre dans l’eau.','Trouver le bon rythme, concilier les opposés et avancer par ajustements patients.'],
['Le Diable','Attachement · désir','Une figure cornue domine deux personnages enchaînés, dont les chaînes semblent pouvoir être retirées.','Voir les dépendances, les peurs ou les désirs qui limitent la liberté; reprendre conscience de son pouvoir de choix.'],
['La Maison Dieu','Rupture · révélation','La foudre frappe une tour; sa couronne tombe et deux silhouettes sont projetées au dehors.','Une structure fragile s’effondre. Le choc peut libérer d’une illusion et permettre de reconstruire sur du vrai.'],
['L’Étoile','Espoir · confiance','Une femme verse de l’eau sur la terre et dans un bassin sous un ciel d’étoiles.','Retrouver confiance, simplicité et inspiration après une période agitée.'],
['La Lune','Rêve · incertitude','Une lune éclaire un chemin entre deux tours; un chien, un loup et une écrevisse apparaissent.','Explorer émotions, rêves et zones floues. Avancer avec prudence sans nier ce que l’intuition ressent.'],
['Le Soleil','Clarté · vitalité','Un enfant à cheval passe devant un mur de tournesols sous un grand soleil rayonnant.','Joie, énergie et compréhension claire. Ce qui était caché devient plus facile à voir et à partager.'],
['Le Jugement','Éveil · bilan','Un ange sonne de la trompette tandis que des personnages se lèvent de leurs tombeaux.','Prendre conscience du chemin parcouru, répondre à un appel et ouvrir un nouveau chapitre.'],
['Le Monde','Accomplissement · unité','Une figure danse au centre d’une couronne, entourée de quatre êtres symboliques.','Aboutissement d’un cycle, intégration et sentiment d’être à sa place avant une prochaine étape.']
];
const suitData={
 wands:{family:'Bâtons',symbol:'des bâtons',entries:[
 ['As','Élan créatif','Une main sort d’un nuage et tend un bâton en bourgeon.','Une idée vive ou une occasion de commencer.'],
 ['Deux','Projet','Une figure tient un globe et regarde l’horizon entre deux bâtons.','Préparer la suite et choisir une direction.'],
 ['Trois','Expansion','Une figure observe des navires au loin, trois bâtons plantés près d’elle.','Les premiers résultats arrivent; le projet peut grandir.'],
 ['Quatre','Célébration','Quatre bâtons forment une arche fleurie devant une scène de fête.','Un moment de stabilité et de joie partagée.'],
 ['Cinq','Concurrence','Cinq personnes brandissent des bâtons dans un échange agité.','Des points de vue s’affrontent; canaliser l’énergie du groupe.'],
 ['Six','Reconnaissance','Un cavalier couronné de laurier traverse une foule avec un bâton.','Une réussite visible et la reconnaissance des efforts.'],
 ['Sept','Défense','Une personne sur une hauteur fait face à six bâtons venant d’en bas.','Tenir sa position avec courage face aux défis.'],
 ['Huit','Mouvement','Huit bâtons traversent rapidement le ciel au-dessus d’un paysage.','Les choses s’accélèrent; agir au bon moment.'],
 ['Neuf','Persévérance','Une personne bandée garde neuf bâtons dressés derrière elle.','La fatigue existe, mais l’endurance protège les acquis.'],
 ['Dix','Charge','Une personne porte difficilement dix bâtons vers une ville.','Trop de responsabilités; alléger ou partager le poids.'],
 ['Valet','Découverte','Un jeune messager contemple son bâton dans un paysage sec.','Curiosité, enthousiasme et premier pas créatif.'],
 ['Cavalier','Audace','Un cavalier lancé en avant tient un bâton dressé.','Passion et mouvement; garder un cap pour éviter la précipitation.'],
 ['Reine','Rayonnement','Une reine tient un bâton fleuri, un tournesol et accueille un chat noir.','Confiance, chaleur et créativité assumée.'],
 ['Roi','Vision','Un roi tient son bâton sur un trône décoré de salamandres.','Leadership inspirant et capacité de mener une idée à terme.']
 ]},
 cups:{family:'Coupes',symbol:'des coupes',entries:[
 ['As','Ouverture du cœur','Une main présente une coupe débordante d’eau sous une colombe.','Naissance d’une émotion, d’un lien ou d’une inspiration.'],
 ['Deux','Rencontre','Deux personnes échangent des coupes sous un caducée ailé.','Réciprocité, accord et lien qui se construit.'],
 ['Trois','Amitié','Trois personnes lèvent leurs coupes dans une ronde festive.','Joie collective, soutien et célébration.'],
 ['Quatre','Repli','Une personne assise ignore une coupe offerte par un nuage.','Prendre du recul sur ses envies sans manquer une occasion.'],
 ['Cinq','Déception','Une figure en manteau regarde trois coupes renversées; deux restent debout.','Accueillir la perte et voir aussi ce qui demeure.'],
 ['Six','Souvenir','Deux enfants échangent une coupe fleurie dans une cour.','Nostalgie, tendresse et retour à une simplicité ancienne.'],
 ['Sept','Possibilités','Sept coupes flottent dans les nuages, pleines d’objets différents.','Beaucoup de désirs ou d’options; distinguer rêve et réalité.'],
 ['Huit','Départ','Une personne s’éloigne de huit coupes sous la lune.','Quitter ce qui ne nourrit plus pour chercher un sens plus profond.'],
 ['Neuf','Satisfaction','Une personne sourit devant neuf coupes disposées en arc.','Plaisir, gratitude et souhait qui se réalise.'],
 ['Dix','Bonheur partagé','Une famille contemple un arc-en-ciel formé de dix coupes.','Harmonie affective et joie dans les liens proches.'],
 ['Valet','Message sensible','Un jeune personnage regarde un poisson surgir d’une coupe.','Surprise émotionnelle, imagination et ouverture.'],
 ['Cavalier','Invitation','Un cavalier avance doucement avec une coupe à la main.','Proposition affective ou créative, portée par le cœur.'],
 ['Reine','Écoute','Une reine contemple une coupe fermée près de la mer.','Empathie, profondeur émotionnelle et écoute intuitive.'],
 ['Roi','Maîtrise émotionnelle','Un roi tient une coupe sur un trône au milieu des eaux.','Calme, compassion et maturité dans les sentiments.']
 ]},
 swords:{family:'Épées',symbol:'des épées',entries:[
 ['As','Clarté','Une main surgit d’un nuage avec une épée couronnée.','Une idée nette, une vérité ou une décision à formuler.'],
 ['Deux','Indécision','Une personne aux yeux bandés croise deux épées devant l’eau.','Un choix demande d’ouvrir les yeux et de regarder les faits.'],
 ['Trois','Peine','Trois épées transpercent un cœur sous la pluie.','Chagrin ou vérité douloureuse à traverser.'],
 ['Quatre','Repos','Une figure allongée repose sous trois épées suspendues.','Pause nécessaire pour retrouver énergie et lucidité.'],
 ['Cinq','Conflit','Une personne ramasse des épées tandis que deux autres s’éloignent.','Victoire amère, tension ou besoin de choisir ses batailles.'],
 ['Six','Transition','Une barque transporte des passagers et six épées vers l’autre rive.','Quitter une situation difficile et avancer vers plus de calme.'],
 ['Sept','Stratégie','Une personne emporte cinq épées en laissant deux derrière elle.','Agir avec discrétion; vérifier aussi la transparence de ses intentions.'],
 ['Huit','Blocage','Une personne bandée et liée se tient au milieu de huit épées.','Des limites ressenties peuvent être reconsidérées.'],
 ['Neuf','Inquiétude','Une personne se redresse dans son lit sous neuf épées.','Anxiété et pensées répétitives; chercher du soutien et du recul.'],
 ['Dix','Fin éprouvante','Une personne est allongée sous dix épées, l’aube pointant au loin.','Un cycle pénible s’achève; le jour revient après l’épreuve.'],
 ['Valet','Vigilance','Un jeune personnage tient une épée levée dans un vent fort.','Curiosité intellectuelle, observation et parole à affiner.'],
 ['Cavalier','Impulsion mentale','Un cavalier fonce, l’épée tendue vers l’avant.','Décision rapide et courage; attention à ne pas brusquer.'],
 ['Reine','Discernement','Une reine lève son épée et tend l’autre main vers l’avant.','Voir clair, poser des limites et parler avec honnêteté.'],
 ['Roi','Autorité intellectuelle','Un roi siège droit avec une épée verticale.','Jugement posé, logique et responsabilité dans la décision.']
 ]},
 pents:{family:'Deniers',symbol:'des deniers',entries:[
 ['As','Occasion concrète','Une main offre un denier au-dessus d’un jardin fleuri.','Une possibilité matérielle à cultiver avec soin.'],
 ['Deux','Adaptation','Une personne jongle avec deux deniers liés par un infini.','Gérer plusieurs priorités en gardant de la souplesse.'],
 ['Trois','Collaboration','Un artisan travaille dans une église sous le regard de deux personnes.','Savoir-faire reconnu et réussite par le travail d’équipe.'],
 ['Quatre','Protection','Une personne tient fermement quatre deniers.','Préserver ses ressources sans se laisser enfermer par la peur de perdre.'],
 ['Cinq','Manque','Deux personnages avancent dans la neige devant un vitrail éclairé.','Précarité ou sentiment d’exclusion; l’aide peut être proche.'],
 ['Six','Partage','Une figure distribue des pièces tout en tenant une balance.','Générosité, soutien et juste équilibre entre donner et recevoir.'],
 ['Sept','Patience','Une personne observe les deniers poussant sur un buisson.','Évaluer le chemin parcouru et laisser du temps aux résultats.'],
 ['Huit','Apprentissage','Un artisan grave patiemment des deniers à son établi.','Pratique régulière, progression et maîtrise d’un métier.'],
 ['Neuf','Autonomie','Une personne se tient dans un jardin riche, un faucon sur la main.','Indépendance et plaisir des fruits de son travail.'],
 ['Dix','Héritage','Une famille se retrouve sous une arche entourée de dix deniers.','Sécurité durable, transmission et richesse des liens.'],
 ['Valet','Étude','Un jeune personnage examine un denier dans ses mains.','Apprendre, préparer un projet concret et rester appliqué.'],
 ['Cavalier','Constante','Un cavalier immobile tient un denier au-dessus des champs.','Avancer avec méthode, fiabilité et persévérance.'],
 ['Reine','Soin concret','Une reine contemple un denier dans un jardin abondant.','Prendre soin des personnes et des ressources avec pragmatisme.'],
 ['Roi','Stabilité','Un roi siège au milieu de vignes et de deniers.','Maîtrise matérielle, responsabilité et générosité durable.']
 ]}
};
const cards=majorData.map((d,i)=>({family:'major',number:i===0?'0':String(i).padStart(2,'0'),title:d[0],key:d[1],visual:d[2],meaning:d[3],image:`major-${String(i).padStart(2,'0')}.jpg`}));
for(const [family,suit] of Object.entries(suitData))suit.entries.forEach((d,i)=>cards.push({family,number:d[0],title:`${d[0]} de ${suit.family}`,key:d[1],visual:d[2],meaning:d[3],image:`${family}-${String(i+1).padStart(2,'0')}.jpg`}));
